Dev permissions
vladysllav/crypto-projects pull request #9
Opened 2024-06-13 15:28 UTC by luckylokki

сделал пермишионы

2024-06-16 13:51 UTC, vladysllav requested changes

2024-06-16 13:51 UTC, vladysllav commented on account_manager/project/serializers.py
> +        project = Project.objects.get(slug=slug, user=self.context["request"].user)
Лучше заюзать get_or_404

2024-06-16 13:51 UTC, vladysllav commented on account_manager/project/serializers.py
> +        credential = Credential.objects.create(project=project, **validated_data)
Не нужно самому создавать, в базовой реализации сериалайзера уже есть методі создания обьекта, лучше через super к нему обратиться

2024-06-16 13:51 UTC, vladysllav commented on account_manager/project/serializers.py
> +        project = Project.objects.get(slug=slug, user=self.context["request"].user)
Тоже самое что и віше

2024-06-16 13:51 UTC, vladysllav commented on account_manager/project/serializers.py
> +        project = Project.objects.create(user=user, **validated_data)
Тоже

2024-06-16 13:51 UTC, vladysllav commented on account_manager/user/views.py
> +        if self.request.user.is_authenticated:
Логику проверки лучше хранить в отдельном методе по типу check_permissions

2024-06-16 14:00 UTC, usik-sviatoslav commented on account_manager/project/serializers.py
> +        project = Project.objects.get(slug=slug, user=self.context["request"].user)
Я бы вообще не использовал метод create в сериалзаторе, так как можно заменить его во вьюсете методом perform_create передав в параметры юзера

2024-06-16 14:04 UTC, usik-sviatoslav commented on account_manager/project/serializers.py
> +        project = Project.objects.get(slug=slug, user=self.context["request"].user)
Для ProjectSerializer передать user, а для TaskSerializer и CredentialSerializer передавать project

2024-06-16 14:16 UTC, usik-sviatoslav commented on account_manager/project/urls.py
> +    path("", ProjectViewSet.as_view({"get": "list", "post": "create"}), name="project_list"),
для чистоты кода я бы вынес словарь в одну переменную, так как везде идут повторения

2024-06-16 14:16 UTC, usik-sviatoslav commented on account_manager/user/views.py
> +        objс = get_object_or_404(User, id=self.kwargs.get("pk"))
Проверь правильность написания objc. У меня пишет что используются `Non-ASCII characters`

2024-06-16 14:16 UTC, usik-sviatoslav commented on account_manager/project/views.py
> +        if not kwargs["project__user"] == self.request.user.id:
я бы положил логику проверки пермишенов как это делается в permission_classes

2024-06-16 14:55 UTC, usik-sviatoslav commented on account_manager/project/views.py
> +        return get_object_or_404(Project, slug=self.kwargs["slug"], user=self.request.user)
тут можно сделать `return get_object_or_404(self.model, **self.kwargs)` так как у нас в url передаются только slug и user_id

2024-06-16 14:56 UTC, usik-sviatoslav commented on account_manager/project/views.py
> +        if not kwargs["project__user"] == self.request.user.id:
тоже самое, логика как в permission_classes

2024-06-16 14:57 UTC, usik-sviatoslav commented on account_manager/project/views.py
> +        if not self.kwargs.get("user_id") == self.request.user.id:
тоже самое, логика как в permission_classes

2024-06-16 15:07 UTC, usik-sviatoslav commented on account_manager/user/views.py
> +        objс = get_object_or_404(User, id=self.kwargs.get("pk"))
и вообще здесь можно прсто `return get_object_or_404(self.model, **self.kwargs)`, только логику проверки пермишенов не забудь так же прикрутить

2024-06-16 15:08 UTC, usik-sviatoslav commented on account_manager/user/views.py
> -    permission_classes = [permissions.AllowAny]
уже есть импорт `from rest_framework.permissions` добавь туда `AllowAny`

2024-06-16 15:11 UTC, usik-sviatoslav commented on account_manager/user/views.py
> +            return [permissions.AllowAny()]
уже есть импорт from `rest_framework.permissions` добавь туда `AllowAny`

2024-06-18 11:38 UTC, vladysllav requested changes

2024-06-18 11:38 UTC, vladysllav commented on account_manager/project/serializers.py
> +        validated_data["project"] = project
Я думаю тут можно просто айди передавать, а не делать запрос на получение проекта целого

2024-06-18 11:38 UTC, vladysllav commented on account_manager/project/serializers.py
> +            "user": self.context["request"].user,
Если ты по айди ищешь проект, то зачем тебе еще и юзер

2024-06-18 11:54 UTC, merged